name: Python CI

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "common/utils/**"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "common/utils/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common/utils

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv-action@v1
        with:
          uv-version: latest

      - name: Verify files in working directory
        run: ls -la

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[test]"

      - name: Run tests
        run: uv run pytest
